In [10]:
import tqdm as notebook_tqdm
from transformers import GPT2LMHeadModel, GPT2Tokenizer, Trainer, TrainingArguments, DataCollatorForLanguageModeling
from datasets import Dataset
import torch
import pandas as pd
import numpy as np
import re

In [11]:
gpt2_tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
gpt2_tokenizer.pad_token = gpt2_tokenizer.eos_token

gpt2_model = GPT2LMHeadModel.from_pretrained("gpt2")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [12]:
def preprocess_text(text):
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

In [13]:
def tokenize_function(examples):
    return gpt2_tokenizer(
        examples["text"],
        truncation=True,
        padding="max_length",
        max_length=128
    )
    
data_collator = DataCollatorForLanguageModeling(
    tokenizer=gpt2_tokenizer,
    mlm=False  
)

training_args = TrainingArguments(
    output_dir="./gpt2_hinglish_finetuned",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    logging_strategy="epoch",
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    save_total_limit=2,
    report_to="none",
    fp16=True
)

/home/shady/Desktop/project/venv/lib64/python3.10/site-packages/transformers/training_args.py:1594: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

In [14]:
chunk_size = 10000
chunk_iterator = pd.read_csv("final_dataset.csv", chunksize=chunk_size)

In [ ]:
# Load the unseen validation set for evaluation
print("Loading unseen validation set for evaluation...")
unseen_df = pd.read_csv("unseen_validation_set.csv")
unseen_df["Conversation"] = unseen_df["Conversation"].astype(str).apply(preprocess_text)
unseen_texts = unseen_df["Conversation"].tolist()

# Create a dataset from the unseen validation data
unseen_dataset = Dataset.from_dict({"text": unseen_texts})
tokenized_unseen = unseen_dataset.map(tokenize_function, batched=True)
tokenized_unseen.set_format("torch", columns=["input_ids", "attention_mask"])

# Process training data in chunks
for chunk_idx, chunk in enumerate(chunk_iterator):
    print(f"\n🚀 Starting training on chunk {chunk_idx + 1}")

    chunk["Conversation"] = chunk["Conversation"].astype(str).apply(preprocess_text)
    chunk_texts = chunk["Conversation"].tolist()

    chunk_dataset = Dataset.from_dict({"text": chunk_texts})
    tokenized_chunk = chunk_dataset.map(tokenize_function, batched=True)
    tokenized_chunk.set_format("torch", columns=["input_ids", "attention_mask"])

    trainer = Trainer(
        model=gpt2_model,
        args=training_args,
        train_dataset=tokenized_chunk,
        eval_dataset=tokenized_unseen,  # Use unseen validation set instead of training data subset
        tokenizer=gpt2_tokenizer,
        data_collator=data_collator
    )

    trainer.train()
    
    # Evaluate on unseen validation set after each chunk
    eval_results = trainer.evaluate()
    print(f"Unseen validation loss: {eval_results['eval_loss']:.4f}")

    gpt2_model.save_pretrained(f"temp/gpt2_hinglish_model_chunk_{chunk_idx + 1}")
    gpt2_tokenizer.save_pretrained(f"temp/gpt2_hinglish_model_chunk_{chunk_idx + 1}")

print("\n✅ Finished training on all chunks. Saving final model...")
gpt2_model.save_pretrained("gpt2_hinglish_model_final")
gpt2_tokenizer.save_pretrained("gpt2_hinglish_model_final")

🚀 Starting training on chunk 1

Map: 100%|██████████| 10000/10000 [00:01<00:00, 5605.03 examples/s]
/tmp/ipykernel_7063/1373692132.py:11: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
`loss_type=None` was set in the config but it is unrecognised.Using the default loss: `ForCausalLMLoss`.

🚀 Starting training on chunk 2

Map: 100%|██████████| 10000/10000 [00:01<00:00, 5000.17 examples/s]
/tmp/ipykernel_7063/1373692132.py:11: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

🚀 Starting training on chunk 3

Map: 100%|██████████| 10000/10000 [00:01<00:00, 9178.95 examples/s]
/tmp/ipykernel_7063/1373692132.py:11: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

🚀 Starting training on chunk 4

Map: 100%|██████████| 10000/10000 [00:01<00:00, 9357.22 examples/s]
/tmp/ipykernel_7063/1373692132.py:11: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

🚀 Starting training on chunk 5

Map: 100%|██████████| 10000/10000 [00:01<00:00, 9417.69 examples/s]
/tmp/ipykernel_7063/1373692132.py:11: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

🚀 Starting training on chunk 6

Map: 100%|██████████| 10000/10000 [00:01<00:00, 9996.60 examples/s]
/tmp/ipykernel_7063/1373692132.py:11: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

🚀 Starting training on chunk 7

Map: 100%|██████████| 10000/10000 [00:01<00:00, 5612.11 examples/s]
/tmp/ipykernel_7063/1373692132.py:11: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

🚀 Starting training on chunk 8

Map: 100%|██████████| 10000/10000 [00:01<00:00, 9861.94 examples/s]
/tmp/ipykernel_7063/1373692132.py:11: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

🚀 Starting training on chunk 9

Map: 100%|██████████| 10000/10000 [00:01<00:00, 9942.88 examples/s]
/tmp/ipykernel_7063/1373692132.py:11: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

🚀 Starting training on chunk 10

Map: 100%|██████████| 10000/10000 [00:01<00:00, 9888.27 examples/s]
/tmp/ipykernel_7063/1373692132.py:11: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

🚀 Starting training on chunk 11

Map: 100%|██████████| 10000/10000 [00:00<00:00, 10086.14 examples/s]
/tmp/ipykernel_7063/1373692132.py:11: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

🚀 Starting training on chunk 12

Map: 100%|██████████| 10000/10000 [00:00<00:00, 10018.73 examples/s]
/tmp/ipykernel_7063/1373692132.py:11: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

🚀 Starting training on chunk 13

Map: 100%|██████████| 10000/10000 [00:00<00:00, 10018.23 examples/s]
/tmp/ipykernel_7063/1373692132.py:11: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

🚀 Starting training on chunk 14

Map: 100%|██████████| 10000/10000 [00:00<00:00, 10064.01 examples/s]
/tmp/ipykernel_7063/1373692132.py:11: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

🚀 Starting training on chunk 15

Map: 100%|██████████| 10000/10000 [00:00<00:00, 10127.99 examples/s]
/tmp/ipykernel_7063/1373692132.py:11: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

🚀 Starting training on chunk 16

Map: 100%|██████████| 10000/10000 [00:01<00:00, 9424.66 examples/s]
/tmp/ipykernel_7063/1373692132.py:11: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

🚀 Starting training on chunk 17

Map: 100%|██████████| 10000/10000 [00:01<00:00, 9686.51 examples/s]
/tmp/ipykernel_7063/1373692132.py:11: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

🚀 Starting training on chunk 18

Map: 100%|██████████| 10000/10000 [00:01<00:00, 9990.23 examples/s]
/tmp/ipykernel_7063/1373692132.py:11: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

🚀 Starting training on chunk 19

Map: 100%|██████████| 10000/10000 [00:01<00:00, 9872.53 examples/s]
/tmp/ipykernel_7063/1373692132.py:11: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

🚀 Starting training on chunk 20

Map: 100%|██████████| 10000/10000 [00:00<00:00, 10195.86 examples/s]
/tmp/ipykernel_7063/1373692132.py:11: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

🚀 Starting training on chunk 21

Map: 100%|██████████| 10000/10000 [00:01<00:00, 9948.72 examples/s]
/tmp/ipykernel_7063/1373692132.py:11: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

🚀 Starting training on chunk 22

Map: 100%|██████████| 10000/10000 [00:01<00:00, 9762.89 examples/s]
/tmp/ipykernel_7063/1373692132.py:11: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

🚀 Starting training on chunk 23

Map: 100%|██████████| 10000/10000 [00:00<00:00, 10089.71 examples/s]
/tmp/ipykernel_7063/1373692132.py:11: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

🚀 Starting training on chunk 24

Map: 100%|██████████| 10000/10000 [00:00<00:00, 10053.59 examples/s]
/tmp/ipykernel_7063/1373692132.py:11: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

🚀 Starting training on chunk 25

Map: 100%|██████████| 10000/10000 [00:00<00:00, 10122.86 examples/s]
/tmp/ipykernel_7063/1373692132.py:11: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

🚀 Starting training on chunk 26

Map: 100%|██████████| 10000/10000 [00:01<00:00, 9885.57 examples/s]
/tmp/ipykernel_7063/1373692132.py:11: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

🚀 Starting training on chunk 27

Map: 100%|██████████| 10000/10000 [00:01<00:00, 9996.78 examples/s]
/tmp/ipykernel_7063/1373692132.py:11: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

🚀 Starting training on chunk 28

Map: 100%|██████████| 10000/10000 [00:00<00:00, 10026.02 examples/s]
/tmp/ipykernel_7063/1373692132.py:11: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

🚀 Starting training on chunk 29

Map: 100%|██████████| 10000/10000 [00:00<00:00, 10000.61 examples/s]
/tmp/ipykernel_7063/1373692132.py:11: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

🚀 Starting training on chunk 30

Map: 100%|██████████| 10000/10000 [00:01<00:00, 9854.91 examples/s]
/tmp/ipykernel_7063/1373692132.py:11: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

✅ Finished training on all chunks. Saving final model...

('gpt2_hinglish_model_final/tokenizer_config.json',
 'gpt2_hinglish_model_final/special_tokens_map.json',
 'gpt2_hinglish_model_final/vocab.json',
 'gpt2_hinglish_model_final/merges.txt',
 'gpt2_hinglish_model_final/added_tokens.json')

## Predict first word

In [16]:
def clean_generated_text(text):
    text = re.sub(r'^[^\w]+|[^\w]+$', '', text)
    return text.strip()

In [17]:
def predict_first_complete_word(input_text, max_new_tokens=10, seed=42):
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

    input_ids = gpt2_tokenizer.encode(input_text, return_tensors="pt").to(device)

    output = gpt2_model.generate(
        input_ids,
        max_new_tokens=max_new_tokens,
        do_sample=True,
        top_k=50,
        temperature=0.7,
        num_return_sequences=1
    )

    generated_text = gpt2_tokenizer.decode(output[0], skip_special_tokens=True)
    print("The text which has been generated from the gpt2 tokens :->  ", generated_text)

    continuation = generated_text[len(input_text):]

    if input_text and not input_text.endswith(' ') and continuation:
        prefix = input_text.split()[-1]
        combined = prefix + continuation

        first_match = re.match(r'^(\S+)', combined)
        if first_match:
            remaining = combined[len(first_match.group(1)):].lstrip()
        else:
            remaining = combined
    else:
        remaining = continuation.lstrip()

    next_match = re.match(r'^(\w+)', remaining)
    next_word = next_match.group(1) if next_match else ""

    return clean_generated_text(next_word)

In [ ]:
input_text = input("Enter a Hinglish phrase: ")
first_word = predict_first_complete_word(input_text)
print("the input text used for generation    :->", input_text)
print(f"First complete word: {first_word}")

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.

The text which has been generated from the gpt2 tokens :->   haan, mujhe bhi yaad hai
the input text used for generation    :-> haan
First complete word: mujhe

:

## Evaluate on unseen validation set

In [ ]:
# Calculate perplexity on the unseen validation set
import math

def calculate_perplexity(model, tokenizer, texts, device, max_length=128):
    model.eval()
    total_loss = 0
    total_tokens = 0
    
    # Limit to a subset if the dataset is too large
    max_samples = min(len(texts), 1000)  # Limit to 1000 samples to avoid memory issues
    texts = texts[:max_samples]
    
    with torch.no_grad():
        for text in notebook_tqdm.tqdm(texts):
            encodings = tokenizer(text, truncation=True, max_length=max_length, return_tensors="pt")
            input_ids = encodings.input_ids.to(device)
            attention_mask = encodings.attention_mask.to(device)
            
            outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=input_ids)
            loss = outputs.loss.item()
            
            # Count only non-padding tokens for accurate perplexity
            num_tokens = attention_mask.sum().item()
            
            total_loss += loss * num_tokens
            total_tokens += num_tokens
    
    # Calculate average loss and perplexity
    avg_loss = total_loss / total_tokens
    perplexity = math.exp(avg_loss)
    
    return perplexity

# Calculate perplexity on training sample
print("Calculating perplexity on training sample...")
training_sample = chunk["Conversation"].tolist()[:500]  # Use a subset of the training data for reference
train_perplexity = calculate_perplexity(gpt2_model, gpt2_tokenizer, training_sample, device)
print(f"GPT-2 Training Sample Perplexity: {train_perplexity:.4f}")

# Calculate perplexity on unseen validation set
print("Calculating perplexity on unseen validation set...")
unseen_perplexity = calculate_perplexity(gpt2_model, gpt2_tokenizer, unseen_texts, device)
print(f"GPT-2 Unseen Validation Perplexity: {unseen_perplexity:.4f}")

In [ ]:
# Save the perplexity results for later comparison
import json
import os

# Check if there's an existing transformer perplexity results file
transformer_perplexities = {}
if os.path.exists("transformer_perplexity_results.json"):
    try:
        with open("transformer_perplexity_results.json", "r") as f:
            transformer_perplexities = json.load(f)
    except json.JSONDecodeError:
        # If the file exists but is corrupted, start with an empty dict
        transformer_perplexities = {}

# Update with GPT-2 results
if "training" not in transformer_perplexities:
    transformer_perplexities["training"] = {}
if "unseen" not in transformer_perplexities:
    transformer_perplexities["unseen"] = {}

transformer_perplexities["training"]["GPT2"] = float(train_perplexity)
transformer_perplexities["unseen"]["GPT2"] = float(unseen_perplexity)

# Save the updated perplexity results
with open("transformer_perplexity_results.json", "w") as f:
    json.dump(transformer_perplexities, f, indent=4)

print("✅ Saved GPT-2 perplexity results to transformer_perplexity_results.json")