In [5]:
import tqdm as notebook_tqdm
from datasets import Dataset
import pandas as pd
import math
import torch
from transformers import XLNetTokenizer, XLNetLMHeadModel, Trainer, TrainingArguments, pipeline

In [6]:
df = pd.read_csv("final_dataset.csv")

# Convert to HuggingFace Dataset using only the Conversation column
dataset = Dataset.from_pandas(df[["Conversation"]].rename(columns={"Conversation": "text"}))
dataset = {"train": dataset}

In [7]:
# Step 3: Load XLNet tokenizer and model

tokenizer = XLNetTokenizer.from_pretrained("xlnet-base-cased")
model = XLNetLMHeadModel.from_pretrained("xlnet-base-cased")

In [8]:
print(dataset["train"])

Dataset({
    features: ['text'],
    num_rows: 300000
})

In [9]:
def tokenize_function(example):
    return tokenizer(example["text"])

tokenized_dataset = dataset["train"].map(tokenize_function, batched=True)

Map: 100%|██████████| 300000/300000 [00:32<00:00, 9202.45 examples/s]

In [10]:
# Grouping function
block_size = 128

def group_texts(examples):
    concatenated = []
    for input_ids in examples["input_ids"]:
        concatenated.extend(input_ids)

    total_length = (len(concatenated) // block_size) * block_size
    input_ids = [concatenated[i : i + block_size] for i in range(0, total_length, block_size)]
    attention_mask = [[1] * block_size for _ in input_ids]

    return {
        "input_ids": input_ids,
        "attention_mask": attention_mask,
        "labels": input_ids.copy(),
    }

In [11]:
# Step 4: Training in 10k chunks with evaluation
chunk_size = 10000
num_chunks = math.ceil(len(df) / chunk_size)
val_accuracies = []

for chunk_idx in range(num_chunks):
    print(f"Training chunk {chunk_idx + 1}/{num_chunks}...")

    chunk_df = df.iloc[chunk_idx * chunk_size : (chunk_idx + 1) * chunk_size]
    dataset = Dataset.from_pandas(chunk_df[["Conversation"]].rename(columns={"Conversation": "text"}))
    tokenized_dataset = dataset.map(tokenize_function, batched=True)
    lm_dataset = tokenized_dataset.map(group_texts, batched=True, remove_columns=tokenized_dataset.column_names)

    # Split into train and validation
    split_idx = int(0.9 * len(lm_dataset))
    train_dataset = lm_dataset.select(range(split_idx))
    eval_dataset = lm_dataset.select(range(split_idx, len(lm_dataset)))

    training_args = TrainingArguments(
        output_dir=f"temp/xlnet-hinglish-chunk{chunk_idx + 1}",
        evaluation_strategy="epoch",
        num_train_epochs=3,
        per_device_train_batch_size=8,
        save_steps=500,
        save_total_limit=2,
        logging_steps=100,
        warmup_steps=100,
        weight_decay=0.01,
        fp16=True,
        overwrite_output_dir=True,
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=eval_dataset,
        tokenizer=tokenizer,
    )

    trainer.train()

    # Evaluate and store accuracy
    eval_result = trainer.evaluate()
    if "eval_loss" in eval_result:
        val_accuracy = 1 - eval_result["eval_loss"]
        val_accuracies.append(val_accuracy)

    # Save intermediate model
    model.save_pretrained(f"temp/xlnet-hinglish-chunk{chunk_idx + 1}")
    tokenizer.save_pretrained(f"temp/xlnet-hinglish-chunk{chunk_idx + 1}")

# Step 5: Final model save
model.save_pretrained("./xlnet-hinglish-final")
tokenizer.save_pretrained("./xlnet-hinglish-final")

Training chunk 1/30...

Map: 100%|██████████| 10000/10000 [00:00<00:00, 10138.88 examples/s]
Map: 100%|██████████| 10000/10000 [00:00<00:00, 52147.85 examples/s]
/home/shady/Desktop/project/venv/lib64/python3.10/site-packages/transformers/training_args.py:1594: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/tmp/ipykernel_13788/1751390237.py:33: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Training chunk 2/30...

Map: 100%|██████████| 10000/10000 [00:01<00:00, 8787.69 examples/s]
Map: 100%|██████████| 10000/10000 [00:00<00:00, 45396.14 examples/s]
/home/shady/Desktop/project/venv/lib64/python3.10/site-packages/transformers/training_args.py:1594: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/tmp/ipykernel_13788/1751390237.py:33: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Training chunk 3/30...

Map: 100%|██████████| 10000/10000 [00:01<00:00, 7967.92 examples/s]
Map: 100%|██████████| 10000/10000 [00:00<00:00, 44174.00 examples/s]
/home/shady/Desktop/project/venv/lib64/python3.10/site-packages/transformers/training_args.py:1594: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/tmp/ipykernel_13788/1751390237.py:33: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Training chunk 4/30...

Map: 100%|██████████| 10000/10000 [00:01<00:00, 8990.52 examples/s]
Map: 100%|██████████| 10000/10000 [00:00<00:00, 48477.57 examples/s]
/home/shady/Desktop/project/venv/lib64/python3.10/site-packages/transformers/training_args.py:1594: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/tmp/ipykernel_13788/1751390237.py:33: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Training chunk 5/30...

Map: 100%|██████████| 10000/10000 [00:01<00:00, 7739.85 examples/s]
Map: 100%|██████████| 10000/10000 [00:00<00:00, 44543.77 examples/s]
/home/shady/Desktop/project/venv/lib64/python3.10/site-packages/transformers/training_args.py:1594: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/tmp/ipykernel_13788/1751390237.py:33: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Training chunk 6/30...

Map: 100%|██████████| 10000/10000 [00:01<00:00, 8814.05 examples/s]
Map: 100%|██████████| 10000/10000 [00:00<00:00, 48349.16 examples/s]
/home/shady/Desktop/project/venv/lib64/python3.10/site-packages/transformers/training_args.py:1594: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/tmp/ipykernel_13788/1751390237.py:33: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Training chunk 7/30...

Map: 100%|██████████| 10000/10000 [00:01<00:00, 8740.25 examples/s]
Map: 100%|██████████| 10000/10000 [00:00<00:00, 44804.81 examples/s]
/home/shady/Desktop/project/venv/lib64/python3.10/site-packages/transformers/training_args.py:1594: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/tmp/ipykernel_13788/1751390237.py:33: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Training chunk 8/30...

Map: 100%|██████████| 10000/10000 [00:01<00:00, 8912.62 examples/s]
Map: 100%|██████████| 10000/10000 [00:00<00:00, 48694.37 examples/s]
/home/shady/Desktop/project/venv/lib64/python3.10/site-packages/transformers/training_args.py:1594: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/tmp/ipykernel_13788/1751390237.py:33: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Training chunk 9/30...

Map: 100%|██████████| 10000/10000 [00:01<00:00, 8157.69 examples/s]
Map: 100%|██████████| 10000/10000 [00:00<00:00, 37776.65 examples/s]
/home/shady/Desktop/project/venv/lib64/python3.10/site-packages/transformers/training_args.py:1594: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/tmp/ipykernel_13788/1751390237.py:33: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Training chunk 10/30...

Map: 100%|██████████| 10000/10000 [00:01<00:00, 7810.90 examples/s]
Map: 100%|██████████| 10000/10000 [00:00<00:00, 48889.56 examples/s]
/home/shady/Desktop/project/venv/lib64/python3.10/site-packages/transformers/training_args.py:1594: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/tmp/ipykernel_13788/1751390237.py:33: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Training chunk 11/30...

Map: 100%|██████████| 10000/10000 [00:01<00:00, 8752.52 examples/s]
Map: 100%|██████████| 10000/10000 [00:00<00:00, 48964.67 examples/s]
/home/shady/Desktop/project/venv/lib64/python3.10/site-packages/transformers/training_args.py:1594: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/tmp/ipykernel_13788/1751390237.py:33: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Training chunk 12/30...

Map: 100%|██████████| 10000/10000 [00:01<00:00, 8175.26 examples/s]
Map: 100%|██████████| 10000/10000 [00:00<00:00, 46255.28 examples/s]
/home/shady/Desktop/project/venv/lib64/python3.10/site-packages/transformers/training_args.py:1594: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/tmp/ipykernel_13788/1751390237.py:33: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Training chunk 13/30...

Map: 100%|██████████| 10000/10000 [00:01<00:00, 9174.82 examples/s]
Map: 100%|██████████| 10000/10000 [00:00<00:00, 50637.68 examples/s]
/home/shady/Desktop/project/venv/lib64/python3.10/site-packages/transformers/training_args.py:1594: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/tmp/ipykernel_13788/1751390237.py:33: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Training chunk 14/30...

Map: 100%|██████████| 10000/10000 [00:01<00:00, 9222.78 examples/s]
Map: 100%|██████████| 10000/10000 [00:00<00:00, 51161.97 examples/s]
/home/shady/Desktop/project/venv/lib64/python3.10/site-packages/transformers/training_args.py:1594: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/tmp/ipykernel_13788/1751390237.py:33: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Training chunk 15/30...

Map: 100%|██████████| 10000/10000 [00:01<00:00, 8589.36 examples/s]
Map: 100%|██████████| 10000/10000 [00:00<00:00, 47748.76 examples/s]
/home/shady/Desktop/project/venv/lib64/python3.10/site-packages/transformers/training_args.py:1594: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/tmp/ipykernel_13788/1751390237.py:33: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Training chunk 16/30...

Map: 100%|██████████| 10000/10000 [00:01<00:00, 9675.74 examples/s]
Map: 100%|██████████| 10000/10000 [00:00<00:00, 49546.67 examples/s]
/home/shady/Desktop/project/venv/lib64/python3.10/site-packages/transformers/training_args.py:1594: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/tmp/ipykernel_13788/1751390237.py:33: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Training chunk 17/30...

Map: 100%|██████████| 10000/10000 [00:01<00:00, 9297.78 examples/s]
Map: 100%|██████████| 10000/10000 [00:00<00:00, 50900.27 examples/s]
/home/shady/Desktop/project/venv/lib64/python3.10/site-packages/transformers/training_args.py:1594: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/tmp/ipykernel_13788/1751390237.py:33: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Training chunk 18/30...

Map: 100%|██████████| 10000/10000 [00:01<00:00, 9493.40 examples/s]
Map: 100%|██████████| 10000/10000 [00:00<00:00, 52423.82 examples/s]
/home/shady/Desktop/project/venv/lib64/python3.10/site-packages/transformers/training_args.py:1594: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/tmp/ipykernel_13788/1751390237.py:33: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Training chunk 19/30...

Map: 100%|██████████| 10000/10000 [00:01<00:00, 8525.14 examples/s]
Map: 100%|██████████| 10000/10000 [00:00<00:00, 47288.54 examples/s]
/home/shady/Desktop/project/venv/lib64/python3.10/site-packages/transformers/training_args.py:1594: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/tmp/ipykernel_13788/1751390237.py:33: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Training chunk 20/30...

Map: 100%|██████████| 10000/10000 [00:01<00:00, 9575.35 examples/s]
Map: 100%|██████████| 10000/10000 [00:00<00:00, 53358.30 examples/s]
/home/shady/Desktop/project/venv/lib64/python3.10/site-packages/transformers/training_args.py:1594: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/tmp/ipykernel_13788/1751390237.py:33: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Training chunk 21/30...

Map: 100%|██████████| 10000/10000 [00:01<00:00, 8689.76 examples/s]
Map: 100%|██████████| 10000/10000 [00:00<00:00, 52266.38 examples/s]
/home/shady/Desktop/project/venv/lib64/python3.10/site-packages/transformers/training_args.py:1594: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/tmp/ipykernel_13788/1751390237.py:33: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Training chunk 22/30...

Map: 100%|██████████| 10000/10000 [00:01<00:00, 9661.90 examples/s]
Map: 100%|██████████| 10000/10000 [00:00<00:00, 52695.31 examples/s]
/home/shady/Desktop/project/venv/lib64/python3.10/site-packages/transformers/training_args.py:1594: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/tmp/ipykernel_13788/1751390237.py:33: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Training chunk 23/30...

Map: 100%|██████████| 10000/10000 [00:01<00:00, 9006.95 examples/s]
Map: 100%|██████████| 10000/10000 [00:00<00:00, 49380.66 examples/s]
/home/shady/Desktop/project/venv/lib64/python3.10/site-packages/transformers/training_args.py:1594: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/tmp/ipykernel_13788/1751390237.py:33: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Training chunk 24/30...

Map: 100%|██████████| 10000/10000 [00:01<00:00, 8856.75 examples/s]
Map: 100%|██████████| 10000/10000 [00:00<00:00, 49383.62 examples/s]
/home/shady/Desktop/project/venv/lib64/python3.10/site-packages/transformers/training_args.py:1594: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/tmp/ipykernel_13788/1751390237.py:33: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Training chunk 25/30...

Map: 100%|██████████| 10000/10000 [00:01<00:00, 9085.04 examples/s]
Map: 100%|██████████| 10000/10000 [00:00<00:00, 49477.35 examples/s]
/home/shady/Desktop/project/venv/lib64/python3.10/site-packages/transformers/training_args.py:1594: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/tmp/ipykernel_13788/1751390237.py:33: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Training chunk 26/30...

Map: 100%|██████████| 10000/10000 [00:01<00:00, 8773.53 examples/s]
Map: 100%|██████████| 10000/10000 [00:00<00:00, 49238.80 examples/s]
/home/shady/Desktop/project/venv/lib64/python3.10/site-packages/transformers/training_args.py:1594: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/tmp/ipykernel_13788/1751390237.py:33: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Training chunk 27/30...

Map: 100%|██████████| 10000/10000 [00:01<00:00, 9099.20 examples/s]
Map: 100%|██████████| 10000/10000 [00:00<00:00, 50004.64 examples/s]
/home/shady/Desktop/project/venv/lib64/python3.10/site-packages/transformers/training_args.py:1594: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/tmp/ipykernel_13788/1751390237.py:33: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Training chunk 28/30...

Map: 100%|██████████| 10000/10000 [00:01<00:00, 8860.77 examples/s]
Map: 100%|██████████| 10000/10000 [00:00<00:00, 45544.77 examples/s]
/home/shady/Desktop/project/venv/lib64/python3.10/site-packages/transformers/training_args.py:1594: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/tmp/ipykernel_13788/1751390237.py:33: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Training chunk 29/30...

Map: 100%|██████████| 10000/10000 [00:01<00:00, 8664.11 examples/s]
Map: 100%|██████████| 10000/10000 [00:00<00:00, 44334.44 examples/s]
/home/shady/Desktop/project/venv/lib64/python3.10/site-packages/transformers/training_args.py:1594: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/tmp/ipykernel_13788/1751390237.py:33: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Training chunk 30/30...

Map: 100%|██████████| 10000/10000 [00:01<00:00, 7936.72 examples/s]
Map: 100%|██████████| 10000/10000 [00:00<00:00, 46004.50 examples/s]
/home/shady/Desktop/project/venv/lib64/python3.10/site-packages/transformers/training_args.py:1594: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/tmp/ipykernel_13788/1751390237.py:33: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

('./xlnet-hinglish-final/tokenizer_config.json',
 './xlnet-hinglish-final/special_tokens_map.json',
 './xlnet-hinglish-final/spiece.model',
 './xlnet-hinglish-final/added_tokens.json')

In [ ]:
generator = pipeline("text-generation", model="./xlnet-hinglish-final", tokenizer=tokenizer)

user_input = input("Enter a prompt: ")
print(f"testing output for the input: {user_input}")
print(generator(user_input))

Device set to use cuda:0

testing output for the input: mai
[{'generated_text': 'mai'}]

: